#!/bin/sh

# PRE-COMMIT HOOK

REPOS="$1"
TXN="$2"

# Exit on all errors.
set -e

# Check for hidden files. These are most likely the result of Solidworks
# crashing.
$REPOS/hooks/checkHiddenFiles.py $REPOS $TXN

# Checks the files to be committed to see if they have an illegal character in their name.
$REPOS/hooks/checkIllegalFilenames.py $REPOS $TXN

# Check that the author of this commit has the rights to perform
# the commit on the files and directories being modified.
$REPOS/hooks/checkNeedsLock.py $REPOS $TXN

# All checks passed, so allow the commit.
exit 0
